---
name: Datalab renovation
on:
  schedule:
    - cron: "0 3 * * *"  # every day at 3am
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Renovate bot
        uses: renovatebot/github-action@v40.1.11
        with:
          renovate-version: full
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/workflows/renovate-config.json
